### ISSUE TITLE
Can't order to hunt

### ISSUE THREAD

**Issue by ttr** [DigitalzombieTLD/FoxCompanion#1]
Hey, 
when I select hunt (b key) and point crosshair on bunny nothing happens. I did saw those errors pop up in console.
`[12:17:05.901] [MelonLoader] [FoxCompanion] [Error] System.NullReferenceException: Object reference not set to an instance of an object
  at FoxCompanion.SnowFoxInputsMain.SnowFoxInputsUpdate () [0x00289] in <cb019669d7b146d4abec3e437f9a8dae>:0
  at FoxCompanion.SnowFoxMain.OnUpdate () [0x0003d] in <cb019669d7b146d4abec3e437f9a8dae>:0
  at MelonLoader.MelonHandler.OnUpdate () [0x000a3] in <ff3b2f38f96a4b158cdd666d5f2930a3>:0
`

**Comment by DigitalzombieTLD** [comment]
Known bug, already fixed for the next release :)

Hunting works currently only on some maps (eg Forlorn Muskeg), due to different naming of the rabbit object in different regions and different object hierarchys.
Forlorn Muskeg: "Animal_Rabbit"
Mystery Lake: "Animal_Rabbit_0"; Animal_Rabbit_1" etc

**Comment by ttr** [comment]
Sure.
Patiently will await next release (as mentioned on discord) :-)

**Comment by GhostWolf66** [comment]
Hello, When I press the letter N the fox is going in the other direction When I press the letter B the fox is not hunting, and waiting please correct the problem

**Comment by GhostWolf66** [comment]
Hello, When I press the letter N the fox is going in the other direction When I press the letter B the fox is not hunting, and, waiting please correct the problem

**Comment by finnjvl** [comment]
_"Hunting works currently only on some maps "_ 
Hmm....Weird, cause it's not workin any region for me, but go to follow is workin in Timberwolf Mountain, fox indeed follow rabbit there, but not hunting.

**Comment by GhostWolf66** [comment]
Hey, Digitalzombie please car driving mode do
or pistol, mode do, or machine, gun mode, do
Digitalzombie, fox mode nice
fox, mode works fine, thank you for, doing it

**Comment by DigitalzombieTLD** [comment]
Fixed!
