### ISSUE TITLE
Mod is broken

### ISSUE THREAD

**Issue by finnjvl** [DigitalzombieTLD/FoxCompanion#2]
After last TLD update or mod settings update, Fox not follow at all, just stand still... So this mod is now fully broken.

**Comment by Silveressa** [comment]
Confirmed, which is a real disappointment, any ETA on an update?

**Comment by DigitalzombieTLD** [comment]
ETA for the next release: Somewhere around the next 32 hours :) 

Problem is already fixed. Still tinkering on rabbit hunting. Currently overhauling the targeting system.

**Comment by Silveressa** [comment]
> ETA for the next release: Somewhere around the next 32 hours :)
> 
> Problem is already fixed. Still tinkering on rabbit hunting. Currently overhauling the targeting system.

Awesome! Looking forward to it!

**Comment by GhostWolf66** [comment]
Hey, Digitalzombie, Please! answer me
please car driving mode do
or pistol, mode do, or machine, gun mode, do

Digitalzombie, fox mode nice

fox, mode works fine, thank you for, doing it

The Long Dark, version v1.76, this mod working

**Comment by DigitalzombieTLD** [comment]
FIXED!

> please car driving mode do
> or pistol, mode do, or machine, gun mode, do

Sorry, no time for car driving. Guns and weapons are not my thing. Doesn't fit in the game in my opinion.

**Comment by Silveressa** [comment]
A small suggestion for the readme file: 

"Players who are upgrading to the latest version from an earlier version need to delete the FoxCompanion.json file from their mod folder first, otherwise the mod will not appear in game."

Other than that momentary hiccup the mod works fantastic! Thanks for updating it!

**Comment by finnjvl** [comment]
> A small suggestion for the readme file:
> 
> "Players who are upgrading to the latest version from an earlier version need to delete the FoxCompanion.json file from their mod folder first, otherwise the mod will not appear in game."
> 
> Other than that momentary hiccup the mod works fantastic! Thanks for updating it!

Best way is do what i do: allways delete old mod file and old  json when update any TLD mods.

**Comment by Silveressa** [comment]
Aye that's what I wound up doing after running into the issue.

A suggestion for a future mod would be a dog/wolf companion? It would be able to hunt rabbits, maybe even deer, and help protect against wolves, but with the downside of needing to fed, and having its injuries treated, much like the NPC survivors from Ep 3 of Wintermute.

Not sure how hard that'd be to code, but it'd be kind of neat having a more intractable companion with additional benefits.

**Comment by finnjvl** [comment]
> A suggestion for a future mod would be a dog/wolf companion? 

I would like to have a dog instead of a fox, maybe some husky or malamute....a sled dog would somehow fit to TLD theme.
I have mod some another games myself, but this C# and C++ coding is same to me than the hieroglyphs of ancient Egypt.

I think wolf protect can be little difficult, but maybe the is one option... using that game torch effect in fox/dog. So use by like the game thinks the fox is a torch to wolfs. I don't know if it's possible, but I guess Digitalzombie may not be able to resist the temptation to try this fox / torch option when such an idea is offered ;)

**Comment by DigitalzombieTLD** [comment]
Damn, I always forget there are comments here too :D

Well ... one could use the fox code as a base for different animals. There shouldn't be much difference, depending on the model.
Some things would need to be restructured and renamed, but thats not very hard. Time consuming? Yes. Hard? No. :)

But if I'd do it now, I'd have two code bases to maintain with kinda the same featureset. Thats not something I *want* to do right now :) Maaaaaybe after the 1.1 release, but I have to many other mod ideas right now. So maybe someone wants to fork the mod then? For now, it's just the fox. 

A whole other story would be to add additional animals to the world, roaming around. That would mean to adapt the TLD AI already used (meh) or writing a whole new one. Could be done, but again veeeeery time consuming.

The torch idea is kinda neat. Would need to take a look how the wolfs react if there are multiple torch (-effects) in the vicinity. Meaning if the player is already holding one. Could be interesting. But then again, not for the fox. Wouldn't seem right.

But ... *sigh* .... I can't let it be ... just bought the whole animal set ^^"
https://assetstore.unity.com/packages/3d/characters/animals/poly-art-animals-forest-set-128568

Maybe additional animals incoming ... we'll see :)
